nekochans/qiita-stocker-backend

.gitignore, composer.json
https://github.com/nekochans/qiita-stocker-backend/issues/11
- `test:coverage` 実行時にプロジェクトルートの `coverage` ディレクトリにHTML形式で出力されている事
- coverageディレクトリがGitの管理対象外になっている事
コードカバレッジ出力のための設定を追加。
phpunit.xmlは、プロジェクト作成時のデフォルトの状態としている。
実装が進んだ段階で、テスト対象を`./app/models`配下に限定する予定であるが、
現時点では`./app/models`が存在せずに、コマンド実行時にエラーとなってまうので変更していない。
=> #11 composer.jsonにtest:coverageコマンドを追加する

app/Exceptions/Handler.php, app/Http/Controllers/AccountController.php, app/Models/Domain/AccountEntity.php, app/Models/Domain/ErrorResponseEntity.php, app/Models/Domain/ErrorResponseEntityBuilder.php, app/Models/Domain/exceptions/AccountCreatedException.php, app/Models/Domain/exceptions/BusinessLogicException.php, app/Models/Domain/exceptions/ValidationException.php, app/Services/AccountScenario.php
https://github.com/nekochans/qiita-stocker-backend/issues/25
- アカウントが作成済みの場合エラーが返されること
APIのエラーのフォーマットを下記の通り定義。
```
{
"code":エラーコード,
"message":"エラーメッセージ",
"errors":{
"フィールド名":[
"エラーエラーメッセージ"
],
}
}
```
`errors`はバリデーション エラーの場合のみ使用される想定。
バリデーション エラーが発生していない場合、送信されない。
例：アカウントが重複して登録された際のエラー
```
{
"code":409,
"message":"既にアカウントの登録が完了しています。"
}
```
- `Model/Domain`に以下の独自の例外クラスを作成
- AccountCreatedException.php
- ValidationException.php
注) `ValidationException.php`について
このIssueでは、バリデーションの実装は行わないが、
APIのエラーレスポンスの実装イメージに必要と判断したため、追加している。
- `ErrorResponseEntity`を作成
独自例外がthrowされた場合、`app/Exceptions/handler.php`内でハンドリングする。
`app/Exceptions/handler.php`にて`ErrorResponseEntity`を生成し、これをもとにJson形式でレスポンスを返す。
テストクラスは別のPRにて対応。
curlで確認した場合、レスポンスがUnicodeエスケープされているため下記のサイトで確認した。
https://www.kwonline.org/u_esc_seq.php
=> アカウント作成APIのエラー処理を作成する

app/Models/Domain/AccountEntity.php, app/Models/Domain/QiitaAccountValue.php, app/Services/AccountScenario.php, tests/Feature/AccountTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/25
- アカウントが既に登録されていた場合のテストケースが作成されていること
- QiitaAccountValueにアカウントが作成済みか確認するメソッド`isCreatedAccount `を追加
- アカウントが作成済みの場合のテストケースを追加
=> アカウント登録時の異常系のテストを追加

app/Infrastructure/Repositories/AccountRepository.php, app/Models/Domain/AccountEntity.php, app/Models/Domain/QiitaAccountValue.php, app/Models/Domain/exceptions/AccountNotFoundException.php, app/Services/LoginSessionScenario.php, tests/Feature/LoginSessionTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/26
- アカウントが作成されていない場合エラーが返されること
ログイン時にアカウントが作成されていない場合にエラーを返す処理を追加。
エラーレスポンスを以下の通り定義。
```
{  
"code":404,
"message":"アカウントが登録されていません。アカウント作成ページよりアカウントを作成してください。"
}
```
Model/Domainに以下の独自の例外クラスを作成
- AccountNotFoundException
=> ログインAPIのエラー処理を作成する

app/Http/Controllers/AccountController.php, app/Models/Domain/QiitaAccountValue.php, app/Models/Domain/exceptions/ValidationException.php, app/Services/AccountScenario.php, tests/Feature/AccountTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/36
- アカウント作成時のバリデーションチェックが追加されていること
- バリデーションエラーの場合、エラーレスポンスが返されること
バリデーション処理を追加し、エラーの場合エラーレスポンスを返すように修正。
`errors`のバリデーションのエラーメッセージについては、画面に表示する予定はないため、Laravelのデフォルトのエラーメッセージ(英語のまま)を利用する。
```
{
"code":422,
"message":"不正なリクエストが行われました。再度、アカウント登録を行なってください。",
"errors":{
"accessToken":["The access token field is required."],
"permanentId":["The permanent id field is required."]
}
}
```
Validatorファザードを使用して、バリデーションを追加。
=> アカウント作成時のバリデーションを追加する

app/Http/Controllers/AccountController.php, app/Models/Domain/LoginSessionEntity.php, app/Models/Domain/exceptions/LoginSessionExpiredException.php, app/Models/Domain/exceptions/UnauthorizedException.php, app/Services/AccountScenario.php, database/factories/AccountFactory.php, tests/Feature/AccountTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/39
- ログインセッションが不正だった場合にエラーが返されること
- 以下のケースにおいて、エラーレスポンスが返るように修正
- Authorizationリクエストヘッダにログインセッションが含まれていない
- ログインセッションがDBに存在しない
- ログインセッションの有効期限が切れている
ログインセッションが不正のケース
```
{
"code":401,
"message":"セッションが不正です。再度、ログインしてください。"
}
```
ログインセッションの有効期限が切れているケース
```
{
"code":401,
"message":"セッションの期限が切れました。再度、ログインしてください。"
}
```
`app/Models/Domain/exceptions`配下に、以下の独自例外を追加。
- UnauthorizedException
- LoginSessionExpiredException
=> 退会APIのログインセッション不正時のエラー処理を作成

app/Infrastructure/Repositories/AccountRepository.php, app/Services/AccountScenario.php, app/Services/LoginSessionScenario.php
https://github.com/nekochans/qiita-stocker-backend/issues/31
- トランザクションが追加されていること
以下のAPIにトランザクション制御処理を追加
- アカウント作成
- アカウント削除
- ログイン
Laravelの手動トランザクションを利用し、トランザクションの開始、コミット、ロールバックを追加。
=> トランザクション制御処理を追加する

app/Infrastructure/Repositories/AccountRepository.php, app/Models/Domain/AccountRepository.php, app/Models/Domain/QiitaAccountValue.php
https://github.com/nekochans/qiita-stocker-backend/issues/48
- Repositoryクラスで`Exception`がThrowされている箇所が`ModelNotFoundException`がThrowされるように修正されていること
Eloquentの`firstOrFail`メソッドを使用し、モデルが見つからなかった場合`Illuminate\Database\Eloquent\ModelNotFoundException`がThrowされるように修正。
=> ModelNotFoundExceptionをThrowするように修正

app/Http/Kernel.php, app/Http/Middleware/XRequestId.php, routes/api.php, tests/Feature/AccountTest.php, tests/Feature/LoginSessionTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/17
- レスポンスHeaderにX-Request-Idが追加されていること
レスポンスHeaderにX-Request-Idを追加。
`app/Http/Middleware`にミドルウェア`XRequestId.php`を作成。
Uuidを生成し、リクエストヘッダーに値を追加している。
=> APIのレスポンスHeaderにX-Request-Idを追加する

composer.json, composer.lock
https://github.com/nekochans/qiita-stocker-backend/issues/5
- Laravelが最新安定版にUpgradeされている事
Laravel 5.7.12 にアップグレード。
アップグレードによる影響は特になし。
=> LaravelをUpgradeする

app/Models/Domain/AccountSpecification.php, app/Models/Domain/LoginSessionSpecification.php, app/Services/AccountScenario.php, app/Services/LoginSessionScenario.php
https://github.com/nekochans/qiita-stocker-backend/issues/45
- アプリケーション層に定義されているバリデーションのビジネスロジックがビジネス層に移動されていること
仕様クラスを作成し、バリデーションロジックをドメイン層に移動した。
- AccountSpecification
- LoginSessionSpecification
それぞれ、アカウント/ログインセッションの作成が可能かどうかを判定する`canCreate`メソッドを作成している。
名前が`canCreate`となっているが、
バリデーションエラーメッセージを取得する必要があるため、配列を戻り値とした。
=> バリデーションのビジネスロジックをドメイン層に移動

app/Infrastructure/Repositories/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryEntityBuilder.php, app/Services/CategoryScenario.php, database/factories/CategoryFactory.php, tests/Feature/AbstractTestCase.php, tests/Feature/CategoryTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/52
- カテゴリがDBに登録されていること
データベースへの保存処理を追加。
`CategoryRepository`に、Eloquentを利用したデータベースへの保存処理を追加。
テストクラスにも、データベースの登録処理を確認するテストケースを追加している。
=> カテゴリのDBへの登録処理を作成する

app/Http/Controllers/CategoryController.php, routes/api.php
https://github.com/nekochans/qiita-stocker-backend/issues/53
- カテゴリ取得APIのIFが定義されていること
カテゴリ作成APIのIFを定義
`GET api/categories`
リクエスト
```
curl -X GET -kv \
-H "Authorization: Bearer e28b5056-6b1b-4f91-a2b5-fdea13f327cb" \
http://127.0.0.1/api/categories
```
```
```
HTTPレスポンスBody
```
[
{
"categoryId":1,
"name":"カテゴリ名1" 
},
{
"categoryId":2,
"name":"カテゴリ名2"
},
{
"categoryId":3,
"name":"カテゴリ名3"
}
]
```
ルーティングを設定
=> カテゴリ取得APIのIFを定義する

app/Infrastructure/Repositories/CategoryRepository.php, app/Models/Domain/AccountEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Providers/AppServiceProvider.php, app/Services/AccountScenario.php, tests/Feature/AccountCreateTest.php, tests/Feature/AccountDestroyTest.php, tests/Feature/AccountIndexTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/63
- 退会APIにカテゴリを削除する処理が追加されていること
退会時にアカウントに紐づくカテゴリを削除する処理を追加
CategoryRepositoryに、アカウントIDから`categories`、`categories_names`テーブルのデータを削除する処理を追加。
これで、画面からの退会処理が可能となった。
また、テストファイルを`AccountCreateTest`と`AccountDestroyTest`に分割した。
=> 退会APIにカテゴリを削除する処理を追加する

app/Http/Controllers/CategoryController.php, routes/api.php
https://github.com/nekochans/qiita-stocker-backend/issues/54
- カテゴリ変更APIのIFが定義されていること
カテゴリ作成APIのIFを定義
`PATCH api/categories/{catgoryId}`
リクエスト
```
curl -X PATCH -kv \
-H "Content-Type: application/json" \
-H "Authorization: Bearer d88f975a-abbb-454c-bf6c-b218fc9b9a67" \
-d \
'
{
"name": "編集したカテゴリ名"
}
' \
http://127.0.0.1/api/categories/12
```
```
```
HTTPレスポンスBody
```
{
"categoryId": "categoryID",
"name": "保存したcategory名",
}
```
ルーティングを設定
=> カテゴリ変更APIのIFを定義する

app/Http/Controllers/CategoryController.php, app/Infrastructure/Repositories/CategoryRepository.php, app/Models/Domain/AccountEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Services/CategoryScenario.php
https://github.com/nekochans/qiita-stocker-backend/pull/73
- 指定されたカテゴリ名が更新されていること
カテゴリ名を更新する処理を追加
`CategoryScenario`に以下の処理を追加
- sessionIDにによる認証処理
- アカウントが持つカテゴリであるかの確認処理
- カテゴリ名の更新処理
テストクラスについては次のPRにて作成する予定。
=> カテゴリ名の変更処理を作成する

app/Providers/AppServiceProvider.php, database/migrations/2018_10_02_070100_create_accounts_qiita_accounts_table.php, database/migrations/2018_10_02_070854_create_accounts_access_tokens_table.php, database/migrations/2018_10_02_072202_create_login_sessions_table.php, database/migrations/2018_11_13_005301_create_categories_names_table.php
https://github.com/nekochans/qiita-stocker-backend/issues/80
- カラムの最大値を変更し、767bytes以上の文字列が入らないようになっていること
- カラムの最大値を191文字に修正
- AppServiceProviderにカラムの長さを191文字に定義する処理を追加
=> カラムの最大値を変更する

app/Http/Controllers/CategoryController.php, app/Models/Domain/Category/CategoryNameValue.php, app/Models/Domain/Category/CategorySpecification.php, app/Services/CategoryScenario.php, tests/Feature/CategoryCreateTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/68
- バリデーションが作成されていること
- バリデーションエラーの場合、エラーレスポンスが返っていること
50文字まで入力した場合のイメージ
カテゴリ名の最大値を50文字に設定。
51文字以上入力された場合、下記のエラーメッセージを返す。
```
カテゴリ名は最大50文字です。カテゴリ名を短くしてください。
```
`app/Models/Domain/Category/CategorySpecification.php`を作成し、バリデーション処理を追加。
=> カテゴリ作成APIのバリデーションを作成する

app/Http/Controllers/CategoryController.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategorySpecification.php, app/Services/CategoryScenario.php, tests/Feature/CategoryUpdateTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/77
- バリデーションが作成されていること
- バリデーションエラーの場合、エラーレスポンスが返っていること
カテゴリIDとカテゴリ名のバリデーションを追加。
カテゴリ作成時のバリデーションと同様に、カテゴリ名の最大値を50文字に設定。
カテゴリIDが不正な場合、下記のエラーメッセージを返す。
```
不正なリクエストが行われました。
```
51文字以上入力された場合、下記のエラーメッセージを返す。
```
カテゴリ名は最大50文字です。カテゴリ名を短くしてください。
```
`app/Models/Domain/Category/CategorySpecification.php`に、カテゴリIDのバリデーションを追加。
カテゴリIDの最大値は、符号無しBIGINTの最大値としている。
=> カテゴリ編集APIのバリデーションを作成する

app/Eloquents/QiitaUserName.php, app/Infrastructure/Repositories/AccountRepository.php, app/Infrastructure/Repositories/CategoryRepository.php, app/Infrastructure/Repositories/LoginSessionRepository.php, app/Models/Domain/Account/AccountEntity.php, app/Models/Domain/Account/AccountEntityBuilder.php, app/Models/Domain/Account/AccountRepository.php, app/Models/Domain/Account/AccountSpecification.php, app/Models/Domain/Category/CategoryRepository.php, app/Models/Domain/LoginSession/LoginSessionEntity.php, app/Models/Domain/LoginSession/LoginSessionEntityBuilder.php, app/Models/Domain/LoginSession/LoginSessionRepository.php, app/Models/Domain/LoginSession/LoginSessionSpecification.php, app/Models/Domain/QiitaAccountValue.php, app/Providers/AppServiceProvider.php, app/Services/AccountScenario.php, app/Services/Authentication.php, app/Services/CategoryScenario.php, app/Services/LoginSessionScenario.php, database/migrations/2018_12_10_004032_create_accounts_qiita_user_names_table.php
https://github.com/nekochans/qiita-stocker-backend/issues/57
- アカウント作成時にQiitaアカウントIDも保存できていること
Qiitaのユーザ名を保存するためのテーブルを作成。
Qiitaのユーザ名を保存するため、マイグレーションファイルを作成。
上記のEloquentモデルを作成。
- `database/migrations/2018_12_10_004032_create_accounts_qiita_user_names_table.php`
- `app/Eloquents/QiitaUserName.php`
また、今回のIssueとは直接関係ないがリファクタリングとして
`app/Models/Domain`配下に`Account`ディレクトリと`LoginSession`ディレクトリを作成。
=> Qiitaのユーザ名を保存するテーブル定義を作成

app/Models/Domain/Account/AccountSpecification.php, app/Models/Domain/LoginSession/LoginSessionSpecification.php, app/Services/AccountScenario.php, app/Services/LoginSessionScenario.php, tests/Feature/AccountCreateTest.php, tests/Feature/LoginSessionTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/57
- アカウント作成APIにユーザ名のバリデーションが追加されていること
- ログインAPIにユーザ名のバリデーションが追加されていること
アカウント作成APIとログインAPIにユーザ名のバリデーションを追加。
ユーザ名のバリデーションを追加し、テストケースも追加。
ユーザ名の最大値は、[ここ](https://github.com/nekochans/qiita-stocker-backend/blob/master/app/Providers/AppServiceProvider.php#L23)で設定した`191`としている。
=> ユーザ名のバリデーションを追加

app/Infrastructure/Repositories/AccountRepository.php, app/Models/Domain/Account/AccountEntity.php, app/Models/Domain/Account/AccountRepository.php, app/Services/LoginSessionScenario.php, tests/Feature/LoginSessionTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/90
- ログイン時にユーザ名が同期されること
ログインAPIにユーザ名を更新する処理を追加。
ユーザ名が変更されているか確認し、変更されていた場合のみユーザ名を更新する処理を追加。
テストついては、ユーザ名が更新されている場合と更新されていない場合の両方のテストケースを作成した。
=> ユーザ名の同期処理を作成する

app/Http/Controllers/StockController.php, app/Http/Middleware/Cors.php, routes/api.php, tests/Feature/StockSynchronize.php
https://github.com/nekochans/qiita-stocker-backend/issues/55
- ストック同期APIのインターフェースが定義されていること
ストック同期APIのIFを定義
`PUT api/stocks`
リクエスト
```
curl -X PUT -kv \
-H "Authorization: Bearer e28b5056-6b1b-4f91-a2b5-fdea13f327cb" \
http://127.0.0.1/api/stocks
```
```
```
HTTPレスポンスBody : なし
ルーティングを設定
テストコードを追加
=> ストック同期APIのインターフェースを定義する

app/Eloquents/Stock.php, app/Eloquents/StockTag.php, database/migrations/2018_12_11_170954_create_stocks_table.php, database/migrations/2018_12_11_173912_create_stocks_tags_table.php
https://github.com/nekochans/qiita-stocker-backend/issues/55
[Qiita APIドキュメント](https://qiita.com/api/v2/docs#get-apiv2usersuser_idstocks)
- データベースが定義されていること
マイグレーションファイルとEloquentモデルを作成。
テーブルは下記を追加。
- stocks
- stocks_tags
- 記事のタイトルは255文字まで入力可能となっていたため、text型を指定
(string型の最大値を191に設定しているため、string型ではなくtext型を指定)
- タグ名については、text型の最大値である`65535`文字以上も登録可能であったが、データ自体が存在しないと思われるためtext型を指定
カテゴリとストックのリレーションは、中間テーブルを作成する予定。
ストックテーブルにカテゴリIDを外部キーとするカラムを追加し、カテゴリとストックのリレーションを作成する方法も検討したが以下の理由により中間テーブルを作成することにした。
- ストックがカテゴリに分類されていない場合、ストックテーブルのカテゴリIDが`null`になってしまう
-> それを回避するために、カテゴリテーブルに`未分類`のカテゴリを作成する方法もあるが、未分類カテゴリがシステム的に作成されたのか、ユーザによって作成されたのかを判断する必要が出てくるため処理が複雑になる
- 現在の仕様ではカテゴリとストックが1対多であるが、もし多対多になった場合には中間テーブルが必要になる
カテゴリとのリレーションにおける考慮が不足していないか。
QiitaAPIのレスポンスの`group`は、QiitaTeamにおいてグループが作成されており、かつ、ストックされた記事の …
=> データベースを定義する

app/Http/Controllers/StockController.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Infrastructure/Repositories/Eloquent/StockRepository.php, app/Models/Domain/Stock/StockRepository.php, app/Providers/AppServiceProvider.php, app/Services/StockScenario.php, database/factories/StockFactory.php, tests/Feature/AbstractTestCase.php, tests/Feature/StockSynchronizeTest.json, tests/Feature/StockSynchronizeTest.php, tests/Feature/TestClientHandler.php
https://github.com/nekochans/qiita-stocker-backend/issues/55
- APIから取得したストックが永続化されていること
ストックをDBに保存する処理を作成。
このPRでは差分の更新は行わない。
Eloquent ORMを利用したDBへの保存処理を作成。
`AppServiceProvider`にて`Guzzle Client`の`handler`をテスト用のモックに変更する処理を追加している。
=> ストックの永続化処理を作成する

app/Http/Controllers/StockController.php, routes/api.php, tests/Feature/StockIndexTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/99
- ストック取得APIのIFが定義されていること
ストック取得APIのIFを定義。
`GET api/stocks`
ページングについては、`Link`ヘッダで返している。
リクエスト
```
curl -X GET -kv \
-H "Authorization: Bearer e28b5056-6b1b-4f91-a2b5-fdea13f327cb" \
http://127.0.0.1/api/stocks?page=1\&per_page=2
```
- page : 1から100まで
- per_page : 1から100まで
```
Total-Count: 9
Link: <http://127.0.0.1/api/stocks?page=4&per_page=2>; rel="next"
<http://127.0.0.1/api/stocks?page=5&per_page=2>; rel="last"
<http://127.0.0.1/api/stocks?page=1&per_page=2>; rel="first"
<http://127.0.0.1/api/stocks?page=2&per_page=2>; rel="prev"
```
HTTPレスポンスBody
```
[
{
"id": 1,
"article_id": "1234567890abcdefghij",
"title": …
```
=> ストック取得APIのIFを定義する

app/Services/StockScenario.php, tests/Feature/StockIndexTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/99
- `article_created_at`の形式が `Y-m-d H:i:s.u` となっていること
`article_created_at`の形式が以下の通りになっていたので、 `Y-m-d H:i:s.u`に修正。
修正前
```
"article_created_at":{
"date":"2014-03-28 16:36:07.000000",
"timezone_type":3,
"timezone":"Asia\/Tokyo"
}
```
修正後
```
"article_created_at":"2014-03-28 16:36:07.000000"
```
=> レスポンスの日付のフォーマットを修正

app/Http/Controllers/LoginSessionController.php, routes/api.php, tests/Feature/AccountDestroyTest.php, tests/Feature/LoginSessionCreateTest.php, tests/Feature/LoginSessionDestroy.php, tests/Feature/LoginSessionDestroyTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/59
- ログアウトAPIのIFが定義されていること
ログアウトAPIのIFを定義
`DELETE api/login-sessions`
リクエスト
```
curl -X DELETE -kv \
-H "Authorization: Bearer 18fc017f-b83b-4f74-8bb3-08807fe056fb"  \
http://127.0.0.1/api/login-sessions
```
```
HTTP/1.1 204 No Content
```
HTTPレスポンスBody : なし
ルーティングを設定
テストコードを追加
=> ログアウトAPIのIFを定義する

app/Http/Controllers/StockController.php, app/Infrastructure/Repositories/Eloquent/AccountRepository.php, app/Models/Domain/Account/AccountRepository.php, app/Models/Domain/Stock/StockEntities.php, app/Models/Domain/Stock/StockSpecification.php, app/Services/StockScenario.php, tests/Feature/StockIndexTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/113
- バリデーションが追加されていること
クエリパラメータ のバリデーションを下記の通り設定。
- page : 1から100まで
- per_page : 1から100まで
```
HTTP/1.1 422 Unprocessable Entity
{
"code":422,
"message":"不正なリクエストが行われました。",
"errors":{"page":["The page field is required."]}
}
```
`errors`は、Laravelのバリデーションメッセージ
仕様クラス`StockSpecification`を作成し、ストック取得時のバリデーションを追加。
=> ストック取得APIにバリデーションを追加する

app/Http/Controllers/CategoryController.php, app/Http/Controllers/StockController.php, database/migrations/2018_12_25_114434_create_categories_stocks_table.php, routes/api.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/100
- APIのIFが定義されていること
- マイグレーションが作成されDBスキーマが定義されていること
カテゴライズAPIのIFを定義
`POST api/categories/stocks`
リクエスト
```
curl -X POST -kv \
-H "Content-Type: application/json" \
-H "Authorization: Bearer 18fc017f-b83b-4f74-8bb3-08807fe056fa" \
-d \
'
{
"id": "1",
"articleIds": ["d210ddc2cb1bfeea9331","d210ddc2cb1bfeea9332","d210ddc2cb1bfeea9333"]
}
' \
http://127.0.0.1/api/categories/stocks
```
```
HTTP/1.1 201 Created
```
HTTPレスポンスBody : なし
ルーティングを設定。
以下のテーブルを作成。
- categories_stocks
=> APIのIFとテーブルを定義する

app/Eloquents/CategoryStock.php, app/Http/Controllers/CategoryController.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Models/Domain/Category/CategorySpecification.php, app/Services/CategoryScenario.php, database/factories/CategoryFactory.php, tests/Feature/AbstractTestCase.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/100
- カテゴリとストックのリレーションのデータが登録されていること
カテゴリとストックのリレーションのデータをDBに保存する処理を追加。
`CategoryScenario`に以下の処理を追加
- セッションIDによる認証処理
- カテゴリIDがアカウントに紐付くカテゴリであるかの判定処理
- カテゴリ`Id`と`ArticleIds`のバリデーション
なお、ArticleIdは[QiitaAPI](https://qiita.com/api/v2/docs#%E6%8A%95%E7%A8%BF)に下記の通り記載があったため、これに相当するバリデーションを行なっている。
```
- id
記事の一意なID
Example: "4bd431809afb1bb99e4f"
Type: string
Pattern: /^[0-9a-f]{20}$/
```
下記のケースについては、別のPRにて対応予定
カテゴリIDとArticleIDのリレーションが既にDBに存在する -> DBにレコードを追加しない
ArticleIDが他のカテゴリに紐づいている場合 -> 既存のリレーションを削除して、新規にレーションを作成
=> カテゴリとストックのリレーションテーブルへの登録処理

app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Services/CategoryScenario.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/100
- カテゴリとストックのリレーションが重複してDBに登録されないこと
- ストックが既に他のカテゴリと紐づいている場合、既存のリレーションが削除されていること
カテゴライズ処理に以下の処理を追加
- カテゴリIDとArticleIDのリレーションが既にDBに存在する場合、DBにレコードを追加しない
- ArticleIDが他のカテゴリに紐づいている場合、 既存のリレーションを削除する
`CategoryEntity`にカテゴライズ処理を作成。
カテゴライズするストック(`ArticleId`)の上限を設定していなかったので、次のPRでバリデーションに追加する。
=> DBへの登録時の差分確認処理を追加する

app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategorySpecification.php, app/Services/CategoryScenario.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/100
- 1度にカテゴライズできるストック数の上限が20件に設定されていること
1度にカテゴライズできるストック数の上限を20件に設定
`CategorySpecification.php`のバリーションに、`articleIds`の最大値を設定。
以下についてもバリデーションの考慮が漏れていたので、合わせて修正している。
- `articleIds`が必須であること
- `articleIds`が配列
また、`articleIds`のIdが重複していた場合、カテゴリとストックのリレーションが重複して登録されてしまっていたため、重複したデータが登録されないように修正した。
=> 1度にカテゴライズできるストック数の上限を追加

app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, tests/Feature/AccountDestroyTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/109
- 退会時に、カテゴリとストックのリレーションテーブルのデータが削除されていること
CategoryIdからカテゴリとストックのリレーションテーブルのデータを削除する処理を追加し、退会処理が行えるように修正。
=> 退会APIにストック情報の削除処理を追加

app/Http/Controllers/StockController.php, routes/api.php, tests/Feature/StockShowCategorizedTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/116
- APIのIFが定義されていること
カテゴライズ済みストックを取得APIのIFを定義。
`GET api/stocks/categories/{id}`
ページングについては、`Link`ヘッダで返している。
リクエスト
```
curl -X GET -kv \
-H "Authorization: Bearer e28b5056-6b1b-4f91-a2b5-fdea13f327cb" \
http://127.0.0.1/api/stocks/categories/1?page=1\&per_page=2
```
- page : 1から100まで
- per_page : 1から100まで
```
Total-Count: 9
Link: <http://127.0.0.1/api/stocks/categories/1?page=4&per_page=2>; rel="next", 
<http://127.0.0.1/api/stocks/categories/1?page=5&per_page=2>; rel="last", 
<http://127.0.0.1/api/stocks/categories/1?page=1&per_page=2>; rel="first", 
<http://127.0.0.1/api/stocks/categories/1?page=2&per_page=2>; rel="prev"
X-Request-Id: …
```
=> カテゴライズ済みのストックを取得するAPIのIFを定義する

app/Http/Controllers/StockController.php, app/Infrastructure/Repositories/Api/QiitaApiRepository.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Models/Domain/Category/CategoryStockEntities.php, app/Models/Domain/Category/CategoryStockEntity.php, app/Models/Domain/Category/CategoryStockEntityBuilder.php, app/Models/Domain/QiitaApiRepository.php, app/Providers/AppServiceProvider.php, app/Services/StockScenario.php, tests/Feature/StockIndexTest.php, tests/Feature/StockShowCategorizedTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/116
- 指定したカテゴリにカテゴライズされたストック一覧が取得できること
カテゴライズされたストック一覧を返すように修正。
- 新規に`CategoryStockEntity`を作成
- `StockScenario`シナリオクラスに、認証処理を追加
- `StockScenario`シナリオクラスに、カテゴリIDから`CategoryStockEntity`のリストを取得し、QiitaAPIから記事の情報を取得する処理を追加
- QiitaAPIへのリクエストに、`Authorization`ヘッダを含めるように修正
-> https://github.com/nekochans/qiita-stocker-backend/issues/114 で作成したストック取得APIについても未対応だったので合わせて対応
バリデーションについては次のPRで対応予定。
QiitaAPIへ同時に複数のリクエストするために`\GuzzleHttp\Promise\all`を使用しているが、QiitaAPIから1件でもエラーとなった場合、エラーレスポンスを返している。
ストックしていた記事が削除されたケースなどを想定すると、エラーレスポンスを返すのではなく、正常に取得できたストックの一覧を返すように修正した方がいいか。
=> ストック取得処理を作成する

app/Http/Controllers/StockController.php, app/Models/Domain/Stock/StockSpecification.php, app/Services/StockScenario.php, tests/Feature/StockShowCategorizedTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/116
- バリデーションが追加されていること
バリデーションを下記の通り設定。
- page : 1から100まで
- per_page : 1から100まで
- categoryId : 1から符号無しBIGINTの最大値まで 
　(https://github.com/nekochans/qiita-stocker-backend/pull/86 カテゴリ編集APIで設定しているカテゴリIDのバリデーションと同じ)
```
HTTP/1.1 422 Unprocessable Entity
{
"code":422,
"message":"不正なリクエストが行われました。",
"errors":{"page":["The page field is required."]}
}
```
`errors`は、Laravelのバリデーションメッセージ
仕様クラス`StockSpecification`に、カテゴライズ済みのストック取得時のバリデーションを追加。
=> バリデーションを追加

app/Http/Controllers/CategoryController.php, routes/api.php, tests/Feature/CategoryDestroyTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/104
- IFが定義されていること
カテゴリ削除APIのIFを定義
`DELETE api/categories/{id}`
リクエスト
```
curl -X DELETE -kv \
-H "Authorization: Bearer 04844f4a-d051-4467-9e6f-911d765e5359" \
http://127.0.0.1/api/categories/1
```
```
HTTP/1.1 204 No Content
```
ルーティングを設定。
=> カテゴリ削除APIのIFを定義する

app/Http/Controllers/CategoryController.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryRepository.php, app/Services/CategoryScenario.php, tests/Feature/AccountDestroyTest.php, tests/Feature/CategoryDestroyTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/104
- カテゴリが削除されていること
カテゴリを削除する処理を追加。
カテゴリを削除する際、カテゴリとストックのリレーションについても削除を行う。
カテゴリIDのバリデーションを追加
- categoryId : 1から符号無しBIGINTの最大値まで 
　(https://github.com/nekochans/qiita-stocker-backend/pull/86 カテゴリ編集APIで設定しているカテゴリIDのバリデーションと同じ)
以下の処理を追加
- 認証処理
- カテゴリIDのバリデーション処理
- カテゴリの削除処理
- categories
- categories_names
- categories_stocks
=> カテゴリ削除処理を作成する

app/Exceptions/Handler.php
https://github.com/nekochans/qiita-stocker-backend/issues/79
- 想定外のエラーのレスポンスが定義されていること
エラーを下記の通り定義
- NotFoundHttpException
code: 404
messege: Not Found
- MethodNotAllowedHttpException
code: 405
messege: Method Not Allowed
- ドメイン層のException、上記に指定したException以外の場合
code: 500
messege: Internal Server Error
`app/Exceptions/Handler.php`に、ドメイン層のException以外の例外のレスポンスを定義
=> 想定外のエラーのレスポンスを定義する

app/Models/Domain/LoginSession/LoginSessionSpecification.php, app/Services/AccountScenario.php, app/Services/LoginSessionScenario.php
https://github.com/nekochans/qiita-stocker-backend/issues/135
- セッションの有効期間が30日間に設定されていること
アカウント作成API、ログインAPIで発行しているセッションの有効期間を30日間に変更。
=> セッションの有効期間を修正する

app/Infrastructure/Repositories/Api/QiitaApiRepository.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryRepository.php, app/Models/Domain/QiitaApiRepository.php, app/Providers/AppServiceProvider.php, app/Services/CategoryScenario.php, database/factories/CategoryFactory.php, database/migrations/2018_12_25_114434_create_categories_stocks_table.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/128
- カテゴライズAPIの中でQIitaAPIへのリクエストを行なっていること
- 取得したストックの情報がDBに保存されていること
カテゴライズAPIに、以下の処理を追加
- QiitaAPIへのリクエスト処理
- 取得したストックの情報をDBに登録する
`categories_stocks`テーブルの定義を、ストックの情報を登録できるように修正。
`CategoryEntity`の`categorize()`に、QiitaAPIへのリクエスト処理、DBへの登録処理を追加。
なお、`CategoryStockEntity`の定義を修正する予定であるが、
カテゴライズ済みのストック一覧を取得するAPI `stocks/categories/{id}`を修正する際に、対応する。
次のPRでは、カテゴライズ済みのストック一覧を取得するAPI `stocks/categories/{id}`を、
DBから取得したストック情報を返すように修正予定。
=> カテゴライズAPIを修正する

app/Http/Controllers/CategoryController.php, app/Infrastructure/Repositories/Api/QiitaApiRepository.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryEntity.php, app/Models/Domain/Category/CategoryStockEntities.php, app/Models/Domain/Category/CategoryStockEntity.php, app/Models/Domain/Category/CategoryStockEntityBuilder.php, app/Models/Domain/QiitaApiRepository.php, app/Services/CategoryScenario.php, app/Services/StockScenario.php, database/factories/CategoryFactory.php, tests/Feature/CategoryCategorizeTest.php, tests/Feature/StockShowCategorizedTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/128
- カテゴライズ済みのストック取得APIが、DBから取得したストック情報をレスポンスとして返していること
- ストックの情報をDBから取得するように修正
`StockScenario`クラスから、QiitaAPIへのリクエスト処理を削除。
`CategoryStockEntity`を修正し、DBから取得したストックをレスポンスに設定している。
また、https://github.com/nekochans/qiita-stocker-backend/pull/139 でカテゴライズAPIの修正を行なったが、QiitaAPIでエラーになった場合の考慮がされていなかったので、エラー処理を追加。
https://github.com/nekochans/qiita-stocker-backend/pull/140/files#diff-94321f889e40a6ff112d866e317dbdefR289
=> カテゴライズ済みのストック取得APIを修正する

app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, app/Models/Domain/Category/CategoryRepository.php, app/Services/StockScenario.php, tests/Feature/StockIndexTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/137
https://github.com/nekochans/qiita-stocker-backend/issues/137 の完了条件が満たされていること
ストックに紐づくカテゴリをレスポンスに追加するため、ストック取得APIのレスポンスを変更。
カテゴリに紐づかない場合は、キー名をレスポンスに含めない。
```
[
{
"stock": {
"id": 1,
"article_id": "1234567890abcdefghij",
"title": "タイトル",
"user_id": "test-user",
"profile_image_url": "http://test.com/test-image.jpag",
"article_created_at": "2018-12-01 00:00:00.000000",
"tags": [
"laravel5.6",
"laravel",
"php"
]
},
"category": {
"categoryId": 1
"name": "カテゴリ１"
}
},
{
"stock": {
"id": 2,
"article_id": "1234567890abcdefghij",
"title": "タイトル2",
"user_id": "test-user2",
"profile_image_url": "http://test.com/test-image2.jpag",
"article_created_at": "2018-12-01 00:00:00.000000",
"tags": [
"laravel5.6",
"laravel",
"php"
]
}
}
]
``` …
=> ストック取得APIのレスポンスにカテゴリを追加する

app/Http/Controllers/StockController.php, app/Infrastructure/Repositories/Eloquent/CategoryRepository.php, tests/Feature/StockShowCategorizedTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/143
https://github.com/nekochans/qiita-stocker-backend/issues/143 の完了条件が満たされていること
カテゴライズ済みのストックを取得するAPIのストックが、新たしくカテゴライズしたストックが先頭になるように修正。
クエリビルダの`orderBy`を使用して、データを取得する際のソート順を`id`の降順に修正。
=> APIのストックのソート順を変更する

app/Http/Kernel.php, app/Http/Middleware/CheckMaintenance.php, routes/api.php
https://github.com/nekochans/qiita-stocker-backend/issues/148
- HTTPメソッドが`OPTIOS`の場合、エラーとならないこと
フロントエンドからリクエストを行なった場合、 HTTPメソッドが`OPTIOS`の際にエラーが発生すると、NetworkErrorとなってしまうため、HTTPメソッドが`OPTIOS`の場合はメンテナンス中のエラーを返さないように修正を行なった。
また、Kernelへの登録の位置がCORS対策のミドルウェアより先になっていたために、CORSエラーが発生していたので、Kernelへの登録箇所を修正。
=> OPTIONSの場合はメンテナンス 中のエラーを返さないように修正

app/Http/Controllers/CategoryController.php, routes/api.php, tests/Feature/CategoryDestroyCategorize.php
https://github.com/nekochans/qiita-stocker-backend/issues/150
- カテゴライズ解除APIのIFが定義されていること
カテゴライズ解除APIのIFを定義
`DELETE api/categories/stocks/{id}`
`{id}`には、下記で指定している`id`が設定される想定。
https://github.com/nekochans/qiita-stocker-backend/blob/master/app/Services/StockScenario.php#L203
リクエスト
```
curl -X DELETE -kv \
-H "Authorization: Bearer 04844f4a-d051-4467-9e6f-911d765e5359" \
http://127.0.0.1/api/categories/stocks/1
```
```
HTTP/1.1 204 No Content
```
カテゴライズ解除APIのルーティングを設定。
=> カテゴライズ解除APIのIFを定義

app/Exceptions/Handler.php, app/Http/Kernel.php, app/Http/Middleware/InfoLogging.php, app/Http/Middleware/XRequestId.php, app/Infrastructure/Logger.php, composer.json, composer.lock, config/logging.php, createDotenv.js
https://github.com/nekochans/qiita-stocker-backend/issues/117
- https://github.com/nekochans/qiita-stocker-backend/issues/117 の完了条件を満たしていること
- 致命的なエラーはSlackのchannelに通知されるようになっていること
こんな感じでSlackに送信される↓（詳しくはSlackのchannelを参照）
Slackに通知する以外にも以下の点が変更されている。
- ログフォーマットがJSON形式に変更（後で加工して集計等がやりやすい為）
- リクエスト毎にinfoログを出力するように変更
infoログは↓のような形
```
{
"log_level": "INFO",
"message": "array (\n)",
"channel": "qiita-stocker-backend",
"trace_id": "dad06702-4aa3-400e-ab51-f5d39d5bf94f",
"file": "/opt/qiita-stocker-backend/app/Http/Middleware/InfoLogging.php",
"line": 30,
"context": {
"response": {
"header": {
"cache-control": [
"no-cache, private"
],
"date": [
"Sun, 03 Feb 2019 06:31:19 GMT"
],
"content-type": [
"application/json"
],
"x-request-id": [
"dad06702-4aa3-400e-ab51-f5d39d5bf94f"
], …
```
=> php-json-loggerを導入し致命的なエラーはSlackに送信するように改修

tests/Feature/AbstractTestCase.php, tests/Feature/CategoryCategorizeTest.php
https://github.com/nekochans/qiita-stocker-backend/issues/141
https://github.com/nekochans/qiita-stocker-backend/issues/141 の完了の条件が満たされていること
auto_increment のリセットするために、`AbstractTestCase::setUp()`において、テーブルのTrancateを行なっていたが、この処理が原因でテストケースにおいてPDOExceptionが発生していた。
PDOExceptionの内容は下記の通りであり、trancateの処理によって、transactionに影響を与えていたと思われる。
```
SAVEPOINT trans2 does not exist
```
Trancateの位置をtearDown()に移動することで、エラーが発生しないように修正した。
なお、修正はテストケースのみに影響がある。全てのテストケースが動作することを確認済み。
=> カテゴライズAPIのPDOExceptionが発生しているテストケースを修正

appspec.yml, hooks/migration.sh
https://github.com/nekochans/qiita-stocker-backend/issues/157
- デプロイ時にMigrationが実行されるようになっていること
CodeDeployでのデプロイ実行時にMigrationを実行するように変更。
@kobayashi-m42 https://github.com/nekochans/qiita-stocker-terraform/pull/46 に書いてある通りで、VPCの内にCodeBuildのプロジェクトを作る事が出来なくて（東京リージョンにはまだ未対応な模様）仕方なくこの方法を実装しているよ・・・🐱
この方法のちょっと嫌なところは、Webサーバーが複数台になった時にMigrationが何回も実行されちゃう事だと思っていて、一時的にこの方法にしたものの、Dockerで運用する時には何とかしたいなと思っている！（すぐ思いつくのはAWS BatchでMigration用のDockerコンテナ作ってそれを任意のタイミングで実行するようにする事）
でも今はAPIサーバーが1台だし問題が起きる可能性は低いから、この方法で実装しているよ！
※ Build用のEC2インスタンスを立てる手もあるけど、その為にEC2を立ち上げるのはあまりに勿体ないし、そもそもEC2にSSHしてMigrationを実行という操作自体がミスを生む原因になると思っているので今はこの方法がベストじゃないけどベターかなって思ってる！
ステージング環境で動作確認済。
料金節約の為、今はRDSとEC2を停止している。
=> デプロイ時にMigrationが実行されるように変更

docker-compose.yml, docker/nginx/Dockerfile, docker/nginx/config/default.conf.template
https://github.com/nekochans/qiita-stocker-backend/issues/173
https://github.com/nekochans/qiita-stocker-backend/issues/173 の完了条件が満たされていること
ローカル開発環境、ECS(EC2モード、Fargateモード)に合わせてnginxのconfが生成されるように修正。
`default.conf.template`に、環境変数`${PHP_HOST}`を設定し、nginxのDockerfileにてconfを生成するように修正。これによって、ECRのリポジトリをEC2モード、Fargateモードで分割する必要がなくなった。
- Fargate
Dockerfileの`ENV PHP_HOST=127.0.0.1`を指定。
- ECS(EC2モード)
タスクの定義で、環境変数`ENV PHP_HOST=php`を設定。Dockerfileの設定より優先される。
→ https://github.com/nekochans/qiita-stocker-terraform/issues/51 で作成中のタスクの定義に追加する予定
- ローカル開発環境
`docker-compose.yml`で環境変数を設定。Dockerfileの設定より優先される。
```
environment:
PHP_HOST: php
```
ECS(EC2モード)で動作することを確認ずみ。
=> 環境変数を利用してnginxのconfを変更する

composer.lock, docker/php/Dockerfile, docker/php/config/docker-php-ext-opcache.ini
https://github.com/nekochans/qiita-stocker-backend/issues/176
https://github.com/nekochans/qiita-stocker-backend/issues/176 の完了条件が満たされていること
イメージを`php:7.3.2-fpm-alpine`に更新。
上記に伴い、`friendsofphp/php-cs-fixer`についてもアップデート。
=> DockerイメージをPHPを7.3に変更する

appspec.yml, buildspec-migration.yml, hooks/migration.sh, hooks/nginx-restart.sh, hooks/php-fpm-restart.sh
https://github.com/nekochans/qiita-stocker-backend/issues/178
- https://github.com/nekochans/qiita-stocker-backend/issues/178 の完了条件を満たしておりAWS上でCodeBuildのBuildが成功する事
- `buildspec-migration.yml` を追加してその中でMigrationを行うように修正
以下の2つのPRと強い関連があるので、これらも同時にマージする必要がある。
- https://github.com/nekochans/qiita-stocker-docker/pull/6
- https://github.com/nekochans/qiita-stocker-terraform/pull/58
以下のように正常にBuild出来る事を確認済。
- 今回の対応でデプロイ時にMigrationを実行する必要がなくなったので削除
- また細かいリファクタリングとしてデプロイ時のserviceコマンドを利用したnginxのrestartコマンドを推奨されている `systemctl` コマンドを使う形に修正。
=> Migration用のbuildspec.ymlを作成

.circleci/config.yml, config/database.php, readme.md
https://github.com/nekochans/qiita-stocker-backend/issues/149
- CircleCI上でBuildが通る状態になっている事
- `.circleci/config.yml` を追加
- ローカルで実行する時の手順をREADMEに追加
@kobayashi-m42 最初、開発用の `docker-compose.yml` を作ってやろうかと思ったけど余計時間がかかりそうだったからCircleCIの公式Dockerイメージを使って作ってあるよ🐱！
いくつかソースコード上にコメントしておいたから確認よろしく！
以下でBuildが通る事を確認済み。
https://circleci.com/gh/nekochans/qiita-stocker-backend/2
=> CircleCIの設定を追加

app/Infrastructure/Logger.php, config/logging.php, createDotenv.js
https://github.com/nekochans/qiita-stocker-backend/issues/188
- 不要になった `USE_IN_DOCKER` による条件分岐が削除されている事
- `USE_IN_DOCKER` による条件分岐を削除
@kobayashi-m42 最初は単純に `USE_IN_DOCKER` を削除するだけで良いかなと思ったけど、↓みたいにログが見にくくなるから、テスト実行時だけは従来通りにログをファイル出力するようにしたから、今まで通り `storage/logs/*` でログを見れるようになっているよ🐱！
https://circleci.com/gh/nekochans/qiita-stocker-backend/26
=> USE_IN_DOCKERによる条件分岐を削除

buildspec-push-ecr.yml
https://github.com/nekochans/qiita-stocker-backend/issues/198
- `aws/codebuild/standard:2.0` で正常にBuildが終了する事
- buildspec.ymlのinstallPHASEにruntime-versionsを追加
今回対象となるのはECRにDockerイメージをプッシュするプロジェクトのみ。
CodeBuildプロジェクトの変更は https://github.com/nekochans/qiita-stocker-terraform/pull/104 にて対応済、ステージング環境で動作確認済。
=> CodeBuildの設定ファイルをaws/codebuild/standard:2.0に変更
